### ISSUE TITLE
ILocalSiteManager subs attribute keeps subsites referenced after deleting.

### ISSUE THREAD

**Issue by agroszer** [zopefoundation/zope.site#1]
`ILocalSiteManager` subs attribute keeps subsites referenced after deleting.
That means you can delete the subsite but the whole will stay in the ZODB because of this attribute.
And that is BAD BAD BAD. Or do I have to "manually" kill that off when removing a subsite?

Copied from
https://bugs.launchpad.net/zope.site/+bug/659162

**Comment by mgedmin** [comment]
I would expect there to be an event subscriber that removes local site registrations on object deletion events.  If that's not the case, one should be added.
