### ISSUE TITLE
Tests currently broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.site#12]
The last time the tests where run was in 2018. I reactivated them and added a cron job to run them weekly. The result is that they are currently broken:

https://travis-ci.org/github/zopefoundation/zope.site/builds/669250982

This could be because of `zope.interface 5`. At least the test breakage is relatively recent as I've not seen such failures in the ZTK test runs before.

**Comment by jamadden** [comment]
It is an incompatibility with zope.interface 5. See https://github.com/zopefoundation/zopetoolkit/pull/40#issuecomment-606641146

**Comment by jamadden** [comment]
Fixed in #13

**Comment by icemac** [comment]
Thank you!
